### ISSUE TITLE
Publish App (5)

### ISSUE THREAD

**Issue by mtxrii** [akayangel218/Project-Bite#44]
* Clean up code
  * [x] Remove unnecessary `console.log()`s
  * [x] Remove unused imports
  * [x] Remove commented-out code
  * [x] Address compile-time warnings
* Host backend app on google app engine (or similar)
* Get new url to access backend app
  * Configure frontend app to send requests to that url
* Create a production version of frontend app
* Host frontend prod version on netlify (or similar)
